#!/opt/eduid/bin/python
#
# List all credentials that have not been used for some time (default 18 months)
#

import sys
import datetime
import pymongo
from pymongo import MongoClient, ReadPreference

def get_username(cred_id, am):
    user = am.find_one({'passwords': { '$elemMatch': { 'id': cred_id } } } )
    if not user:
        return ''
    return '{!r}'.format(user.get('eduPersonPrincipalName'),
                         )

days = 18 * 30
if len(sys.argv) == 2:
    days = int(sys.argv[1])

client = MongoClient('mongodb://mongodb.docker:27017/', read_preference=ReadPreference.SECONDARY)

coll = client['eduid_idp_authninfo']['authn_info']
am = client['eduid_am']['attributes']

before = datetime.datetime.now() - datetime.timedelta(days = days)

print("Looking for credentials not used since {!s}".format(before))

for cred in coll.find({'success_ts': {'$lte': before}}):
    print("{_id!s} {ts} {user}".format(
            _id = cred['_id'],
            ts = cred['success_ts'],
            user = get_username(cred['_id'], am)
            ))
